---

name: "Ansible Lint Action"
description: "Run Ansible Lint on playbooks"
inputs:
  ansible_version:
    description: "Specify Ansible version"
    required: false
    default: "latest"
  python_version:
    description: "Specify Python version"
    required: false
    default: "3.9"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "${{ inputs.python_version }}"

    - name: Install Ansible and Ansible Lint
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install "ansible==${{ inputs.ansible_version }}" ansible-lint

    - name: Run Ansible Lint
      shell: bash
      run: ansible-lint
