---

name: "Ansible Lint Action"
description: "Installs Ansible and runs Ansible Lint on code"
inputs:
  ansible_version:
    description: "Version of Ansible to install"
    required: false
    default: '2.17'
  python_version:
    description: "Python version to install"
    required: false
    default: '3.10'
    
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install Ansible and Ansible Lint
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install "ansible==${{ inputs.ansible_version }}" ansible-lint

    - name: Run Ansible Lint
      shell: bash
      run: ansible-lint .
