---

name: Ansible Lint Workflow

on:
  workflow_call:
    inputs:
      ansible_version:
        description: 'Specify Ansible version'
        default: 'latest'
        required: false
      python_version:
        description: 'Specify Python version'
        default: '3.9'
        required: false

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Ansible Lint
        uses: dbond007/github-cicd-library/actions/ansible-lint@main
        with:
          ansible_version: ${{ inputs.ansible_version }}
          python_version: ${{ inputs.python_version }}
