---

name: Ansible Lint Workflow

on:
  workflow_call:
    inputs:
      ansible_version:
        description: 'Specify the version of Ansible to use'
        required: false
        default: 'latest'
        type: string
      python_version:
        description: 'Specify the Python version to use'
        required: false
        default: '3.9'
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Ansible Lint Action
        uses: dbond007/github-cicd-library/.github/actions/ansible-lint-action@main
        with:
          ansible_version: ${{ inputs.ansible_version }}
          python_version: ${{ inputs.python_version }}
